In [1]:
import numpy as np

In [2]:
test = np.arange(15).reshape(3, 5)
test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
test = np.arange(100).reshape(2, 2, 5, 5)
test

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24]],

        [[25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]]],


       [[[50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59],
         [60, 61, 62, 63, 64],
         [65, 66, 67, 68, 69],
         [70, 71, 72, 73, 74]],

        [[75, 76, 77, 78, 79],
         [80, 81, 82, 83, 84],
         [85, 86, 87, 88, 89],
         [90, 91, 92, 93, 94],
         [95, 96, 97, 98, 99]]]])

In [8]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.linspace(0, 3, 5)

array([0.  , 0.75, 1.5 , 2.25, 3.  ])

In [14]:
import random
random.randint(0, 6)

2

In [15]:
a = []
for i in range(100):
    a.append(random.randint(1, 6))

In [19]:
a.count(4)

15

In [20]:
a = np.random.rand(5)
print(a)

[0.56778971 0.33472663 0.71051213 0.45380927 0.15103838]


In [21]:
a * 2

array([1.13557942, 0.66945326, 1.42102426, 0.90761853, 0.30207675])

In [22]:
np.random.random((4, 5))

array([[0.89137832, 0.51066148, 0.42941815, 0.99692251, 0.98631313],
       [0.60887385, 0.11036216, 0.83050288, 0.56232952, 0.10315624],
       [0.88519324, 0.57309046, 0.67966523, 0.21384715, 0.14520483],
       [0.12455046, 0.3829608 , 0.46660975, 0.11387689, 0.29580148]])

In [28]:
a = np.arange(14).reshape(2, 7)
a

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [25]:
np.arange(14).reshape(2, 7).min()

0

In [26]:
np.arange(14).reshape(2, 7).max()

13

In [27]:
np.arange(14).reshape(2, 7).sum()

91

In [29]:
a.sum(axis=1)

array([21, 70])

In [30]:
a.sum(axis=0)

array([ 7,  9, 11, 13, 15, 17, 19])

In [32]:
a = np.floor(10* np.random.rand(2, 5))
a

array([[6., 4., 6., 3., 6.],
       [5., 0., 7., 2., 5.]])

In [33]:
np.arange(14).reshape(2, 7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [34]:
np.arange(14).reshape(2, 7).T

array([[ 0,  7],
       [ 1,  8],
       [ 2,  9],
       [ 3, 10],
       [ 4, 11],
       [ 5, 12],
       [ 6, 13]])